### ISSUE TITLE
Creating scope with  "backend_type": "AZURE_KEYVAULT" not available

### ISSUE THREAD

**Issue by javabeanuser** [databricks/databricks-cli#279] opened 2020-03-03 06:39 UTC
Dear Team, 
I have to create scope with type AZURE_KEYVAULT

Like this: 
{
            "name": "key-vault-sec",
            "scope": "users",
            "backend_type": "AZURE_KEYVAULT",
            "keyvault_metadata": {
                "resource_id": "/subscriptions/fcXXXXXXXXXXXXXXba/resourceGroups/XXXXXXXXXXXXXXXXXXX/providers/Microsoft.KeyVault/vaults/HMDP-KeyVault-Test",
                "dns_name": "https://XXXX-keyvault-XXXX.vault.azure.net/"
            },
            "is_databricks_managed": false
}

However I cant due to not having that parameters in API request.

Obviously it is not available now. Would you mind sharing with me a solution for this?

Thanks.

**Comment by nfx** [comment] 2022-05-04 17:49
Duplicate of #338

**Closed by nfx** 2022-05-04 17:49 UTC
